import { Service, Doctor, Testimonial, GalleryItem } from '@/types'

export const services: Service[] = [
  {
    id: 'dental-implants',
    title: 'Dental Implants',
    description: 'Permanent titanium-root tooth replacement that looks, feels, and functions exactly like natural teeth.',
    icon: 'Hammer',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800',
    longDescription: 'Dental implants are the gold standard for tooth replacement. Premium titanium posts fuse with your jawbone, providing a permanent foundation for custom-crafted porcelain crowns. A lifetime solution.',
    benefits: ['Permanent solution', 'Natural look & feel', 'Preserves jawbone', 'Lifetime durability'],
    duration: '2-3 sessions',
    price: '₹1,24,999',
  },
  {
    id: 'smile-design',
    title: 'Smile Design',
    description: 'Digital smile makeover — preview your perfect smile before treatment begins.',
    icon: 'Wand2',
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800',
    longDescription: 'Using advanced digital imaging, we design your perfect smile before a single procedure. Every detail — shape, shade, proportion — is calibrated to your facial features for a natural, stunning result.',
    benefits: ['Digital preview', 'Custom designed', 'Natural results', 'Complete transformation'],
    duration: '3-4 sessions',
    price: '₹2,09,999',
  },
  {
    id: 'teeth-whitening',
    title: 'Teeth Whitening',
    description: 'Professional Zoom! whitening — up to 8 shades brighter in one session.',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800',
    longDescription: 'Professional-grade whitening with our Zoom! light-activated system. Safe, painless, and delivers noticeable results in a single visit. Remove years of staining in under an hour.',
    benefits: ['Results in one session', 'Safe and painless', 'Long-lasting', 'Removes deep stains'],
    duration: '60 min',
    price: '₹24,999',
  },
  {
    id: 'root-canal',
    title: 'Root Canal',
    description: 'Gentle, pain-free root canal therapy using modern micro-surgical techniques.',
    icon: 'HeartPulse',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800',
    longDescription: 'Our gentle root canal therapy uses dental microscopes and advanced anesthesia for a completely comfortable experience. Preserve your natural tooth and eliminate pain.',
    benefits: ['Saves natural tooth', 'Pain-free procedure', 'Quick recovery', 'Prevents spread'],
    duration: '90 min',
    price: '₹74,999',
  },
  {
    id: 'orthodontics',
    title: 'Orthodontics',
    description: 'Clear aligners and precision braces for perfectly aligned teeth.',
    icon: 'AlignCenter',
    image: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=800',
    longDescription: 'Invisalign clear aligners or modern ceramic braces — both discreet, both effective. 3D digital planning maps every tooth movement for predictable, beautiful results.',
    benefits: ['Discreet options', 'Comfortable', 'Faster results', 'Improved oral health'],
    duration: '6-18 months',
    price: '₹2,89,999',
  },
  {
    id: 'pediatric-dentistry',
    title: 'Pediatric Dentistry',
    description: 'Fun, gentle care for children in a calming, child-friendly environment.',
    icon: 'Smile',
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=800',
    longDescription: 'Our pediatric specialists create positive dental experiences for children. Preventive care, education, and gentle treatment in an atmosphere designed to make kids feel safe and excited.',
    benefits: ['Child-friendly', 'Preventive focus', 'Education & habits', 'Comfortable visits'],
    duration: '30-45 min',
    price: '₹12,499',
  },
  {
    id: 'cosmetic-dentistry',
    title: 'Cosmetic Dentistry',
    description: 'Porcelain veneers, composite bonding, and complete smile transformations.',
    icon: 'Palette',
    image: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=800',
    longDescription: 'Premium porcelain veneers and composite bonding crafted by our cosmetic artists. Transform your smile with custom-matched shade, shape, and translucency for breathtaking results.',
    benefits: ['Instant transformation', 'Natural aesthetics', 'Custom color matching', 'Long-lasting'],
    duration: '2-3 sessions',
    price: '₹1,59,999',
  },
  {
    id: 'laser-dentistry',
    title: 'Laser Dentistry',
    description: 'Minimally invasive laser treatments for gums, cavities, and soft tissue.',
    icon: 'Syringe',
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=800',
    longDescription: 'State-of-the-art laser technology for pain-free gum treatments, cavity preparation, and soft tissue procedures. Faster healing, less bleeding, and superior precision.',
    benefits: ['Minimal discomfort', 'Faster healing', 'Precision treatment', 'Less bleeding'],
    duration: '30-60 min',
    price: '₹34,999',
  },
]

export const doctors: Doctor[] = [
  {
    id: 'dr-wasi',
    name: 'Dr. Wasi Ahmed',
    title: 'Chief Dental Surgeon',
    specialization: 'Cosmetic & Implant Dentistry',
    experience: '15+ years',
    education: 'BDS, MDS - AIIMS Delhi',
    certifications: ['American Board of Cosmetic Dentistry', 'AAID Implant Fellow', 'Invisalign Premier'],
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800',
    bio: 'World-renowned cosmetic dentist with over 15 years of experience. Trained at AIIMS Delhi, specializing in complex full-mouth rehabilitations and implantology.',
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday'],
  },
  {
    id: 'dr-fatima',
    name: 'Dr. Fatima Khan',
    title: 'Senior Orthodontist',
    specialization: 'Orthodontics & Aligners',
    experience: '12+ years',
    education: 'BDS, MDS Orthodontics - Manipal',
    certifications: ['Invisalign Diamond Plus', 'ICOI India', 'Clear Braces Expert'],
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=800',
    bio: 'Brings precision and artistry to orthodontic care. Advanced training in clear aligner therapy with thousands of successful smile transformations.',
    availability: ['Monday', 'Tuesday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-omar',
    name: 'Dr. Omar Hassan',
    title: 'Periodontist',
    specialization: 'Gum Health & Implants',
    experience: '10+ years',
    education: 'BDS, MDS Periodontology - KGMU',
    certifications: ['Indian Society of Periodontology', 'Laser Surgery Certified', 'Implant Specialist'],
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800',
    bio: 'Periodontist specializing in gum health and laser surgery. Expertise in minimally invasive periodontal therapy with exceptional outcomes.',
    availability: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  {
    id: 'dr-leila',
    name: 'Dr. Leila Rahman',
    title: 'Pediatric Dentist',
    specialization: "Children's Dentistry",
    experience: '8+ years',
    education: 'BDS, MDS Pediatric - SRM Chennai',
    certifications: ['Indian Board of Pediatric Dentistry', 'Sedation Dentistry Certified', 'Child Psychology Focus'],
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800',
    bio: 'Creates warm, joyful experiences for children. Her gentle approach and child-friendly techniques make every visit something kids look forward to.',
    availability: ['Monday', 'Wednesday', 'Thursday', 'Saturday'],
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Priya Sharma',
    role: 'Smile Design Patient',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    rating: 5,
    content: 'Life-changing experience. Dr. Wasi transformed my smile and my confidence. The digital preview showed me exactly what to expect — and the result exceeded it.',
  },
  {
    id: 't2',
    name: 'Arjun Mehta',
    role: 'Dental Implants Patient',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    rating: 5,
    content: 'World-class care. The implants feel completely natural. The clinic is stunning, the technology is incredible, and the team made every step comfortable.',
  },
  {
    id: 't3',
    name: 'Ananya Reddy',
    role: 'Invisalign Patient',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    rating: 5,
    content: 'Best decision I ever made. Clear aligners were so comfortable and the digital tracking showed my progress in real time. Six months, perfect smile.',
  },
  {
    id: 't4',
    name: 'Rohan Desai',
    role: 'Teeth Whitening Patient',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    rating: 5,
    content: 'Incredible results from one session. Multiple shades whiter, completely comfortable, and the staff was professional throughout. Highly recommended.',
  },
  {
    id: 't5',
    name: 'Aisha Patel',
    role: 'Root Canal Patient',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
    rating: 5,
    content: 'I was terrified of root canals but Dr. Omar made it completely painless. Felt nothing, recovered quickly, and saved my natural tooth.',
  },
  {
    id: 't6',
    name: 'Vikram Singh',
    role: 'Full Smile Makeover',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    rating: 5,
    content: 'Every step was perfectly planned. The digital preview showed me my future smile. The outcome is even better than I imagined. Truly premium experience.',
  },
]

export const galleryItems: GalleryItem[] = [
  {
    id: 'g1',
    beforeImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600',
    afterImage: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600',
    title: 'Complete Smile Makeover',
    description: 'Porcelain veneers & whitening',
    category: 'Cosmetic',
  },
  {
    id: 'g2',
    beforeImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600',
    afterImage: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=600',
    title: 'Full Mouth Implants',
    description: 'Single arch restoration',
    category: 'Implants',
  },
  {
    id: 'g3',
    beforeImage: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=600',
    afterImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600',
    title: 'Invisalign Alignment',
    description: '6-month transformation',
    category: 'Orthodontics',
  },
  {
    id: 'g4',
    beforeImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600',
    afterImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600',
    title: 'Zoom Whitening',
    description: 'Professional whitening result',
    category: 'Cosmetic',
  },
  {
    id: 'g5',
    beforeImage: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600',
    afterImage: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=600',
    title: 'Veneer Transformation',
    description: '8 porcelain veneers',
    category: 'Cosmetic',
  },
  {
    id: 'g6',
    beforeImage: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600',
    afterImage: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=600',
    title: 'Gum Contouring',
    description: 'Laser gum reshaping',
    category: 'Periodontal',
  },
]

export const heroSlides = [
  {
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1920',
    alt: 'Modern luxury dental clinic interior',
  },
  {
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=1920',
    alt: 'Professional dentist consultation',
  },
  {
    image: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1920',
    alt: 'Advanced dental treatment room',
  },
  {
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=1920',
    alt: 'Happy patient smile transformation',
  },
  {
    image: 'https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=1920',
    alt: 'High-tech dental equipment',
  },
]

export const floatingCards = [
  { title: 'Dental Implants', desc: 'Permanent tooth replacement', color: '#00D4FF' },
  { title: 'Smile Makeover', desc: 'Complete transformation', color: '#3B82F6' },
  { title: 'Root Canal', desc: 'Pain-free therapy', color: '#60A5FA' },
  { title: 'Orthodontics', desc: 'Perfect alignment', color: '#00D4FF' },
  { title: 'Cosmetic', desc: 'Premium veneers', color: '#3B82F6' },
]

export const siteContent = {
  hero: {
    title: 'Crafting Confident Smiles Through Advanced Dental Excellence',
    subtitle: 'Luxury dental care powered by advanced technology, expert specialists, and personalized treatment experiences.',
    rating: 4.9,
    patients: '10,000+',
    experience: '20+ Years',
    stats: [
      { label: 'Happy Patients', value: '5000+' },
      { label: 'Success Rate', value: '98%' },
      { label: 'Years Experience', value: '20+' },
      { label: 'Patient Rating', value: '4.9★' },
    ],
  },
  about: {
    title: 'Redefining Dental Excellence',
    content: 'At Wasi Dental Clinic, we combine advanced technology with artistic precision to create smiles that transform lives. Our state-of-the-art facility offers a premium experience in a serene, luxurious environment.',
    mission: 'To provide world-class dental care in a comfortable, luxurious setting using the latest technology.',
    vision: 'To be the leading destination for premium cosmetic and restorative dentistry.',
  },
  contact: {
    address: '7, Wasi Dental House, Marine Drive, Mumbai - 400001',
    phone: '+91 98765 43210',
    email: 'hello@wasidental.com',
    hours: {
      'Monday - Saturday': '10:00 AM - 8:00 PM',
      'Sunday': 'Closed',
    },
    emergency: '+91 98765 43211',
  },
  social: {
    facebook: 'https://facebook.com/wasidental',
    instagram: 'https://instagram.com/wasidental',
    twitter: 'https://twitter.com/wasidental',
    youtube: 'https://youtube.com/wasidental',
    linkedin: 'https://linkedin.com/company/wasidental',
  },
}

export const faqItems = [
  {
    q: 'How often should I visit the dentist?',
    a: 'We recommend every six months for routine check-ups and cleaning. Your specific needs may vary based on your oral health condition.',
  },
  {
    q: 'Do you accept dental insurance?',
    a: 'Yes, we accept most major insurance plans. Our team will help verify your coverage and maximize your benefits before treatment.',
  },
  {
    q: 'Is teeth whitening safe?',
    a: 'Absolutely. Our professional whitening uses FDA-approved compounds supervised by dental experts for complete safety and effectiveness.',
  },
  {
    q: 'How long do dental implants last?',
    a: 'With proper care, dental implants can last a lifetime. We use premium materials and advanced techniques for optimal long-term outcomes.',
  },
  {
    q: 'Do you offer payment plans?',
    a: 'Yes, flexible financing options through CareCredit and in-house payment plans to make your treatment affordable.',
  },
  {
    q: 'What should I expect on my first visit?',
    a: 'Comprehensive examination, digital X-rays, professional cleaning, and a personalized treatment plan discussion.',
  },
]
